import React from "react";
import { connectToDatabase } from "../../lib/mongodb";
import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import Hstyle from "@/components/helpers/Hstyle";
import Timetable from "@/components/widgets/Timetable";
import Infotable from "@/components/widgets/Infotable";
import OneList from "@/components/widgets/OneList";
import PicCherch from "../../public/images/hero2.webp";

export default function Home({ list, gospel, news }) {
  return (
    <>
      <Head>
        <title>
          Греко-католицька парафія Різдва Пресвятої Богородиці мкр.Дравці
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="border-t border-gray-300 border-b-gray-200 flex items-center text-dark w-full bg-fixed bg-center bg-cover custom_img">
        <Layout className="bg-lightG/90 min-h-screen pt-0 md:pt-16 sm:pt-8 grid place-items-center h-screen"
        >
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2">
              <Image
                src={PicCherch}
                alt="Церква Різдва Богородиці"
                className="w-full h-auto inline-block"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>

            <div className="ml-5 md:ml-0 flex-col items-center self-center text-left">
              <h1
                className="w-full mx-auto py-2 flex items-center justify-center
                 text-center overflow-hidden sm:py-0
                 font-mont text-royalNavy font-bold capitalize
                 text-4xl md:text-3xl sm:text-2xl"
              >
                Греко-Католицька парафія Різдва Пресвятої Богородиці мкр.Дравці
              </h1>
              <OneList doc={list} />
            </div>
          </div>
        </Layout>
      </main>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-16 sm:pt-8">
          <Hstyle text="Розклад" />
          <div className="mt-5 sm:w-full">
            <Timetable text="start" doc={list} hiding={true} />
          </div>
        </Layout>
      </main>
      <section className="flex items-center text-dark w-full">
        <Layout className="pt-8">
          <Hstyle text="Проповіді" />
          <Infotable
            postsS={gospel}
            collection={"List_Gospel"}
            pathPage={"/"}
            pathN={""}
            n_folder={""}
            router={null}
            hiding={true}
          />
        </Layout>
      </section>
      <section className="flex items-center text-dark w-full">
        <Layout className="pt-8">
          <Hstyle text="Новини" />
          <Infotable
            postsS={news}
            collection={"List_News"}
            pathPage={"/"}
            pathN={""}
            n_folder={""}
            router={null}
            hiding={true}
          />
        </Layout>
      </section>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const { db } = await connectToDatabase();
    const list = await db
      .collection("List_Day")
      .aggregate([
        {
          $addFields: {
            dayAsDate: {
              $dateFromString: {
                dateString: "$_day",
                format: "%d.%m.%Y",
              },
            },
          },
        },
        {
          $sort: {
            dayAsDate: 1,
          },
        },
      ])
      .toArray();

      const gospel = await db
        .collection("List_Gospel")
        .find({})
        .limit(1)
        .sort({ $natural: -1 })
        .toArray();

      const news = await db
        .collection("List_News")
        .find({})
        .limit(2)
        .sort({ $natural: -1 })
        .toArray();

    return {
      props: {
        list: JSON.parse(JSON.stringify(list)),
        gospel: JSON.parse(JSON.stringify(gospel)),
        news: JSON.parse(JSON.stringify(news)),
      },
    };
  } catch (e) {
    console.error(e);
  }
}
