import React from "react";
import ReactPlayer from "react-player";
import { connectToDatabase } from "../../lib/mongodb";
import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import Hstyle from "@/components/helpers/Hstyle";
import Timetable from "@/components/widgets/Timetable";
import Infotable from "@/components/widgets/Infotable";
import OneList from "@/components/widgets/OneList";

export default function Home({ list, gospel, news }) {
  return (
    <>
      <Head>
        <title>
          Греко-католицька парафія Різдва Пресвятої Богородиці мкр.Дравці
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="border-t border-gray-300 border-b-gray-200 flex items-center text-dark w-full relative">
        <Layout className="min-h-screen pt-0 md:pt-16 sm:pt-8 grid place-items-center h-screen">
          <div className="flex items-center justify-between w-full lg:flex-col rounded-lg bg-light1 border border-light1 ">
            <div className="w-1/2">
              <Image
                src="/images/nativite.jpeg"
                width={100}
                height={100}
                alt="Церква Різдва Богородиці"
                className="w-full h-auto inline-block rounded-lg ml-2 mt-2.5 mb-2.5"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>

            <div className="ml-5 md:ml-0 flex-col items-center self-center text-left">
              <h1
                className="w-full mx-auto py-2 flex items-center justify-center
                 text-center overflow-hidden sm:py-0
                 font-mont text-royalNavy font-bold capitalize
                 text-4xl md:text-3xl sm:text-2xl"
              >
                {"Греко-Католицька парафія Різдва Пресвятої Богородиці"}
              </h1>
              <p
                className="w-full mx-auto py-2 flex items-center justify-center
                 text-center overflow-hidden sm:py-0
                 font-mont text-royalNavy font-bold
                 text-4xl md:text-3xl sm:text-2xl"
              >
                мкр. Дравці
              </p>
              <OneList doc={list} />
            </div>
          </div>
        </Layout>
      </main>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-16 sm:pt-8">
          <Hstyle text="Розклад" />
          <div className="mt-5 sm:w-full">
            <Timetable text="start" doc={list} hiding={true} />
          </div>
        </Layout>
      </main>
      <section className="flex items-center text-dark w-full">
        <Layout className="pt-8">
          <Hstyle text="Проповіді" />
          <Infotable
            postsS={gospel}
            collection={"List_Gospel"}
            pathPage={"/"}
            pathN={""}
            n_folder={""}
            router={null}
            hiding={true}
          />
        </Layout>
      </section>
      <section className="flex items-center text-dark w-full">
        <Layout className="pt-8">
          <Hstyle text="Новини" />
          <Infotable
            postsS={news}
            collection={"List_News"}
            pathPage={"/"}
            pathN={""}
            n_folder={""}
            router={null}
            hiding={true}
          />
        </Layout>
      </section>
      <section className="flex items-center text-dark w-full">
        <Layout className="pt-8">
          <Hstyle text="Контанкти" />
          <div className="mt-5 sm:w-full">
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10557.696192339188!2d22.325410000000005!3d48.58257900000001!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47391bde37af41d3%3A0xa82320aab776021a!2z0KbQtdGA0LrQstCwINCg0ZbQt9C00LLQsCDQn9GA0LXRgdCy0Y_RgtC-0Zcg0JHQvtCz0L7RgNC-0LTQuNGG0ZY!5e0!3m2!1suk!2sua!4v1683050758815!5m2!1suk!2sua"
              width="600"
              height="450"
              style={{ border: 0 }}
              allowFullScreen=""
              loading="lazy"
              referrerPolicy="no-referrer-when-downgrade"
            />
          </div>
        </Layout>
      </section>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const { db } = await connectToDatabase();
    const list = await db
      .collection("List_Day")
      .aggregate([
        {
          $addFields: {
            dayAsDate: {
              $dateFromString: {
                dateString: "$_day",
                format: "%d.%m.%Y",
              },
            },
          },
        },
        {
          $sort: {
            dayAsDate: 1,
          },
        },
      ])
      .toArray();

    const gospel = await db
      .collection("List_Gospel")
      .find({})
      .limit(1)
      .sort({ $natural: -1 })
      .toArray();

    const news = await db
      .collection("List_News")
      .find({})
      .limit(2)
      .sort({ $natural: -1 })
      .toArray();

    return {
      props: {
        list: JSON.parse(JSON.stringify(list)),
        gospel: JSON.parse(JSON.stringify(gospel)),
        news: JSON.parse(JSON.stringify(news)),
      },
    };
  } catch (e) {
    console.error(e);
  }
}
